let mainDishes= [
        { "course" : "Chicken Tikka Masala (mittelscharf)",
        "price" : "14,50",
        "info" : "Hühnerfilet in exotischen Gewürzen mariniert mit einer mittelscharfen Sauce, im Lehmofen gegrillt.",
        },
        { "course" : "Chicken Korma",
        "price" : "14,90",
        "info" : "Hühnerfleisch-Stücke in einer milden Sahne-Currysauce mit Nüssen.",
        },
        { "course" : "Chicken Curry",
        "price" : "13,90",
        "info" : "Hühnerfleisch in einer würziger Currysauce",
        },
        { "course" : "Mango Chicken",
        "price" : "14,90",
        "info" : "Hühnerfleisch mit Mango in einer milden Currysauce.",
        },
        { "course" : "Butter Chicken",
        "price" : "14,90",
        "info" : "Gegrilltes Hähnchenbrustfilet in Tomaten-Butter-Sahnesauce.",
        },
        { "course" : "Karahi Chicken (mittelscharf)",
        "price" : "13,90",
        "info" : "indische Spezialitäten mit Hühnerbrustfilet, mittelscharfer Sauce, Zwiebeln, Paprika, Knoblauch, Ingwer und Tomaten.",
        },
    ]
let sideDishes = [
        { "course" : "Plain Reis",
        "price" : "4,00",
        "info" : "Reis ohne alles.",
        },
        { "course" : "Egg Reis",
        "price" : "6,50",
        "info" : "gebratener Reis mit Ei und Gewürzen.",
        },
        { "course" : "Plain Naan",
        "price" : "2,75",
        "info" : "Indisches Brot aus hellem Weizenmehl zubereitet",
        },
        { "course" : "Cheese Naan",
        "price" : "4,90",
        "info" : "Indisches Brot gefüllt mit hausgemachtem Käse.",
        },
    ]

let desserts = [
        { "course" : "Gulab Jamoon",
        "price" : "4,50",
        "info" : "Gebratene süße Milchbällchen.",
        },
        { "course" : "Rasmalai Käsebällchen",
        "price" : "5,50",
        "info" : "In cremiger Milch eingetaucht.",
        },
        { "course" : "Mango Lassi 0,4l",
        "price" : "4,00",
        "info" : "hausgemacht mit Joghurt, Milch und Mango",
        },
    ]


let basketCourses = [
    {   "course" : "",
        "price" : "",
    }
]